# Generated by Django 4.0.4 on 2022-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_profilewishlist_wishlistproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cartItem',
            field=models.BooleanField(default=False),
        ),
    ]
