# Generated by Django 4.0.4 on 2022-04-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_product_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic1',
            field=models.FileField(blank=True, null=True, upload_to='ProdcutImg'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.FileField(blank=True, null=True, upload_to='ProdcutImg'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic3',
            field=models.FileField(blank=True, null=True, upload_to='ProdcutImg'),
        ),
    ]
